### ISSUE TITLE
Allow noise to be posterized with weighted colors 

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/NoiseTool#1]
Basically you could define a couple rgb values + their weights, and the preview could look something like this
![image](https://user-images.githubusercontent.com/73215501/104391946-24c04300-5595-11eb-8c2f-53bcf559010a.png)
Would make visualizing palettes much easier

**Comment by dfsek** [comment]
Implemented in 570ead3088681ba6f23da2dc32674685b8a9a12e
